controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    bubble.tossBubble()
    bubble.load_bubble()
})
controller.right.onEvent(ControllerButtonEvent.Repeated, function () {
    bubble.tilt_angle(bubble.Choice.Right)
})
scene.onHitWall(SpriteKind.Bubble, function (sprite, location) {
    bubble.stick_to_wall(sprite, location)
})
controller.left.onEvent(ControllerButtonEvent.Repeated, function () {
    bubble.tilt_angle(bubble.Choice.Left)
})
bubble.createBoard()
bubble.load_bubble()
let mySprite = sprites.create(img`
    ...............77cc........
    .............c777cc.ccc....
    .............777cccccccc...
    .............c7ccccccccc...
    ............ce2eccccccccc..
    ............cd322cccccccc..
    ............23422cccccccc..
    ......c222..2222eccccccccc.
    ....7c2d422cce22ccccccccccc
    ..77772d222ce22ccceeeeceeec
    .777cce222223222cceeeeeee..
    ..ccccc22ecdd222eec...cc...
    ...cccccccc22222eee........
    .cccccccccee222cccee.......
    ccccccccccee7cccccee.......
    ccccccccee.77cccccee.......
    .cccccceee.77ccccccec......
    .77cccce....cccccccce......
    .cccccc....ccccccccee......
    .cee.cc....ccccccccee......
    .eee.........ccccccee......
    .............ccccccee......
    ................ccccc......
    ...................cc......
    `, SpriteKind.Player)
mySprite.top = 102
